### PR TITLE
Added clues on screenshots

### PR DESCRIPTION
**Pull request by stappersg**
It was unclear how the .png files in screenshots directory were made.

The shoelaces-overview.png can be generated by

   make shoelaces-overview.png

(and `make shoelaces-o[TAB][ENTER]` will most likely do the same.)

Just `make` will create `config` file and prints an invite for taking a closer look at the Makefile.

Doing

   make shoelaces-frontend-1.png

starts `shoelaces` and invites for webbrowser and screenshotcapture action.

Signed-off-by: Geert Stappers <stappers@stappers.it>

### CODE REVIEW

**Comment by raul-te** [comment]
Thanks for this contribution! I made a few adjustments.  I don't think a Makefile is the best way for conveying the instruction for taking the screenshots, as they're highly interactive. I moved your ideas to a README and completed the missing piece for `shoelaces-frontend-2.png`. I'm also bringing your screenshots from #28, as I prefer keeping highly related contributions in the same PR.

**Comment by stappersg** [comment]
Avoiding another "co-authored by".

**Comment by stappersg** [comment]
On Tue, Jan 17, 2023 at 12:00:25PM -0800, Geert Stappers wrote:
> Avoiding another "co-authored by".

No hard feelings.

(I have tomorrow time to resubmit the  .msc file.)

**Comment by raul-te** [comment]
> Avoiding another "co-authored by".

Oh, I was about to merge. What's wrong with that? Anyway, let me know if you intend to open another PR with these changes. I don't mind if you squash everything under your name, so it's not co-authored. Also, if you prefer me not to commit to your PRs and only provide review suggestions, I'm fine with that as well. Your contributions are highly appreciated!

**Comment by stappersg** [comment]
FWIW there is now #32

**Pull request closed without merging**
