### PR TITLE
Segregate BindAddr and BaseURL

### PR DESCRIPTION
**Pull request by raul-te**

### CODE REVIEW

**Comment by raul-te** [comment]
@the-maldridge would you mind taking a look?

**Comment by the-maldridge** [comment]
Sure, I can spin a build and test this in my cluster this evening.

**Comment by the-maldridge** [comment]
Overall looks okay.  I would suggest that since `-base-url` is now the only component that needs to be altered externally to adjust the Dockerfile like so:

```

ENTRYPOINT ["/shoelaces", "-data-dir", "/data", "-static-dir", "/web"]
CMD []
```

This will remove the need for downstreams to need to re-specify the web directory and data directory which should generally be the defaults specified unless a custom theme is being loaded.

**Comment by raul-te** [comment]
Thanks, that makes sense. I'll implement that change and merge.

**Pull request merged**
